---

- name: disable landing mode
  file:
    dest: "/etc/nginx/landing.html"
    state: absent
  become: yes
  become_user: root

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded
  become: yes
  become_user: root

