---

- name: Enable maintenance mode
  import_tasks: enable.yml
  when: enable_maintenance | default(false)

- name: Disable maintenance mode
  import_tasks: disable.yml
  when: disable_maintenance | default(false)

