- name: Set Certbot package names (Ubuntu >= 20.04)
  set_fact:
    certbot_name: certbot
    certbot_nginx_name: python3-certbot-nginx
  when: ansible_distribution_version >= "20.04"

- name: Set Certbot package names (Ubuntu < 20.04)
  set_fact:
    certbot_name: certbot
    certbot_nginx_name: python-certbot-nginx
  when: ansible_distribution_version < "20.04"

# Only needed on older Ubuntu (< 20.04) — kept this for safety
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
  when: ansible_distribution_version < "20.04"

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install certbot
  apt:
    name: "{{ certbot_name }}"
    state: present

- name: Install certbot-nginx plugin
  apt:
    name: "{{ certbot_nginx_name }}"
    state: present

- import_tasks: certificate.yml
  when: domain_name is defined
